### ISSUE TITLE
RateLimitPolicy API v2

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/architecture#13]
High-level tasks related to [RateLimitPolicy API v2](https://github.com/Kuadrant/architecture/blob/main/rfcs/0001-rlp-v2.md) (see Kuadrant/architecture#12)

- [x] Upgrade GWAPI to v0.7.0
- [x] Kuadrant/kuadrant-operator#156
- [x] Kuadrant/wasm-shim#35
- [x] Document behavior of Direct PA → Route RLP fully _replaces_ Gateway RLP (i.e. GW RLP is an implicit default)
- [x] Implement API spec [validation rules](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules)
- [ ] ~Implement validating webhook~
- [x] Implement reconciliation of RLP/status (ref: Kuadrant/architecture#9)
- [x] Kuadrant/kuadrant-operator#215
- [x] Inherited Policy Attachment
- [ ] CLI to reflect "effective policies"
- [ ] ~CLI to migrate across versions (?)~
- [ ] More resources to target (e.g. Service, Namespace) (?)

**Comment by guicassolato** [comment]
Closing this as essentially done.

The remaining open items are beyond the scope of what needs to be done strictly for the RateLimitPolicy, or somewhat covered by issues such as https://github.com/Kuadrant/kuadrant-operator/issues/810, https://github.com/Kuadrant/kuadrant-operator/issues/761, https://github.com/Kuadrant/kuadrant-operator/issues/821 and https://github.com/Kuadrant/kuadrant-operator/issues/830.
