### ISSUE TITLE
Basic DNSPolicy in a single cluster context

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/architecture#31]
High level tasks relating to https://github.com/Kuadrant/architecture/pull/30

- [x] https://github.com/Kuadrant/multicluster-gateway-controller/issues/496
- [x] https://github.com/Kuadrant/multicluster-gateway-controller/issues/311
- [x] https://github.com/Kuadrant/multicluster-gateway-controller/issues/646
- [x] https://github.com/Kuadrant/multicluster-gateway-controller/issues/655

Follow Up:
https://github.com/Kuadrant/architecture/issues/67

**Comment by maleck13** [comment]
Removed the provider ref change into its own epic https://github.com/Kuadrant/multicluster-gateway-controller/issues/715

**Comment by maleck13** [comment]
Follow up to this epic https://github.com/Kuadrant/multicluster-gateway-controller/issues/716 additional improvments
