### ISSUE TITLE
Implement RFC 0004: Policy Status

### ISSUE THREAD

**Issue by didierofrivia** [Kuadrant/architecture#38]
After agreeing on the proposal described in [Policy Status](https://github.com/Kuadrant/architecture/blob/main/rfcs/0004-policy-status.md) the actual implementation needs to be done. In order to do so, the following list shows where it needs to be applied:

**Kuadrant Operator**:
* [x] AuthPolicy
  * [x] [ Accepted Condition](https://github.com/Kuadrant/kuadrant-operator/pull/347)
  * [x] [Enforced Condition ](https://github.com/Kuadrant/kuadrant-operator/pull/411)
* [x] RateLimitPolicy
  * [x] [ Accepted Condition](https://github.com/Kuadrant/kuadrant-operator/pull/347)
  * [x] [Enforced Condition ](https://github.com/Kuadrant/kuadrant-operator/issues/414)

**MCG Controller**:
* [x] DNSPolicy
  * [x] [ Accepted Condition](https://github.com/Kuadrant/multicluster-gateway-controller/issues/640) https://github.com/Kuadrant/kuadrant-operator/pull/416
  * [x] [Enforced Condition ](https://github.com/Kuadrant/multicluster-gateway-controller/issues/641) https://github.com/Kuadrant/kuadrant-operator/pull/449
* [x] TLSPolicy
  * [x] [ Accepted Condition](https://github.com/Kuadrant/multicluster-gateway-controller/issues/642) https://github.com/Kuadrant/kuadrant-operator/pull/416
  * [x] [Enforced Condition ](https://github.com/Kuadrant/kuadrant-operator/issues/572) https://github.com/Kuadrant/kuadrant-operator/pull/635

**Related Issues**
- https://github.com/Kuadrant/kuadrant-operator/issues/87
- https://github.com/Kuadrant/kuadrant-operator/issues/140
- https://github.com/Kuadrant/kuadrant-operator/issues/290

**Comment by alexsnaps** [comment]
@maleck13 Could you have a look at this means for MCG

**Comment by KevFan** [comment]
Updated the description to reflect the issues / PRs that are done and those that still need to be done for the respective policies

**Comment by KevFan** [comment]
Closing as functionally complete
