### ISSUE TITLE
Distributed tracing on data plane

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/architecture#48]
As request come into the cluster, it'd be nice to enable distributed traces from the Gateway onward, throughout the different Kuadrant components and eventually to the user's application fronted by Kuadrant.

 - [x] Kuadrant/kuadrant-operator#399
 - [x] Kuadrant/authorino-operator#167
 - [x] Kuadrant/wasm-shim#47
 - [x] Kuadrant/wasm-shim#48
 - [x] Kuadrant/limitador#86
 - [x] Kuadrant/limitador#275
 - [x] Kuadrant/limitador-operator#130
 - ~Add some global way (in the `Kuadrant` CR?) to configure the underlying components for them to push spans to the OTLP collector.~ Moved to https://github.com/Kuadrant/kuadrant-operator/issues/731
 - ~Have us (within wasm, e.g. pre auth RL?) start the trace and is there a way to have envoy propagate that traceparent to ext`-auth?~ Moved to https://github.com/Kuadrant/wasm-shim/issues/59
 - ~Look into adding "well-known" fields into our span to "trace" them back to the user's domain: RLP, AP, …~ Moved to https://github.com/Kuadrant/architecture/pull/96

**Comment by david-martin** [comment]
@alexsnaps @adam-cattermole for the sake of gh issue hygiene, and assuming at this time there are no issues in this epic progressing, how about closing this out with the tasks that were completed & marking this as Done?
The remaining tasks could be moved to a new epic and prioritised accordingly.

**Comment by adam-cattermole** [comment]
Sure, I think that makes sense - breaking out the pieces / decisions around how we expose tracing at the kuadrant level

**Comment by david-martin** [comment]
Closing as done with follow up work captured in:
- https://github.com/Kuadrant/kuadrant-operator/issues/731
- https://github.com/Kuadrant/wasm-shim/issues/59
- https://github.com/Kuadrant/architecture/pull/96
