### ISSUE TITLE
Single Policy Controller Hub Changes (unified Kuadrant phase 2)

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/architecture#69]
Phase 2 will add better handling of this though to ensure only relevant polices are processed in each deployment (spoke: auth, ratelimit, hub: dns, tls)

**Phase 2**

- [x] https://github.com/Kuadrant/kuadrant-operator/issues/398
- [ ] https://github.com/Kuadrant/multicluster-gateway-controller/issues/772
- [ ] https://github.com/Kuadrant/multicluster-gateway-controller/issues/773
- [x] https://github.com/Kuadrant/multicluster-gateway-controller/issues/774

**Related**

Policy Sync https://github.com/Kuadrant/multicluster-gateway-controller/issues/430
